Fast-forward changes over the past year*
*azure integrations have been omitted

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -28,8 +28,8 @@ variables:
   - group: pipeline-variable-group
   - name: DOCKER_BUILDKIT
     value: 1
-  - name: tag
-    value: $(build.buildId)
+  - name: buildVersionTag
+    value: $(build.SourceVersion)
   - name: isMain
     value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
   - name: buildBaseImage
@@ -37,7 +37,14 @@ variables:
   - name: builderImageName
     value: $(CONTAINER_REGISTRY_DOMAIN)/$(CONTAINER_REPOSITORY)_builder:latest
   - name: imageName
-    value: $(CONTAINER_REGISTRY_DOMAIN)/$(CONTAINER_REPOSITORY):$(tag)
+    value: $(CONTAINER_REGISTRY_DOMAIN)/$(CONTAINER_REPOSITORY):$(build.SourceVersion)
+  # only works if you have a main branch
+  - name: dockerTag
+    ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
+      value: latest
+    ${{ else }}:
+      value: latest-branch
+
 
 resources:
   containers:
@@ -113,82 +120,88 @@ stages:
 
   - stage: Build
     displayName: Build and Push
-    condition: and(succeeded(), eq(variables.isMain, 'true'))
+    dependsOn: "" # Run in parallel with tests for faster cycles
+    pool: prod-agents-no-docker
     jobs:
       - job: BuildBase
         displayName: Build and Push Base
-        condition: and(succeeded(), or(eq(variables['Build.Reason'], 'Schedule'), eq(variables.buildBaseImage, 'true')))
+        condition:  eq(variables.buildBaseImage, 'true')
         steps:
-          - task: Docker@2
-            displayName: Login to ACR
+          - script: |
+              if [ -z "$(GITHUB_PAT_EXPIRY)" ]; then
+                echo "GITHUB_PAT_EXPIRY is not set! This is for your own good!"
+                exit 1
+              fi
+
+              echo "GitHub PAT expires on $(GITHUB_PAT_EXPIRY)"
+
+              now=$(date +%s)
+              expiry=$(date -d "$(GITHUB_PAT_EXPIRY)" +%s)
+
+              if [ $expiry -lt $now ]; then
+                echo "GitHub PAT is expired. ACR task will fail to pull from GitHub."
+                echo "Please follow instructions in config/terraform/README.md to update."
+                exit 1
+              fi
+            displayName: Confirm GitHub PAT is not expired
+          - task: AzureCLI@2
+            displayName: Build and push base image to ACR
             inputs:
-              command: login
-              containerRegistry: $(ACR_SERVICE_ENDPOINT_NAME)
-          - task: Docker@2
-            displayName: Build base image
-            inputs:
-              command: build
-              containerRegistry: $(ACR_SERVICE_ENDPOINT_NAME)
-              repository: $(CONTAINER_REPOSITORY)_builder
-              buildContext: $(Build.Repository.LocalPath)
-              Dockerfile: config/docker/builder/Dockerfile
-              arguments: "--no-cache"
-              tags: |
-                $(tag)
-                latest
-          - task: Docker@2
-            displayName: Push base image to ACR
-            inputs:
-              command: push
-              containerRegistry: $(ACR_SERVICE_ENDPOINT_NAME)
-              repository: $(CONTAINER_REPOSITORY)_builder
-              tags: |
-                $(tag)
-                latest
-          - task: Docker@2
-            displayName: Logout of ACR
-            inputs:
-              command: logout
-              containerRegistry: $(ACR_SERVICE_ENDPOINT_NAME)
+              azureSubscription: SC-IHRBENCHMARK-P-WEU-RG01
+              scriptType: bash
+              scriptLocation: inlineScript
+              inlineScript: |
+                set -ex
+                az acr task run \
+                  --registry=$(CONTAINER_REGISTRY_NAME) \
+                  --name=build-base-image \
+                  --arg DOCKER_IMAGE_TAG=$(buildVersionTag) \
+                  --arg DOCKER_IMAGE_TAG=$(dockerTag) \
+                  --context=https://github.com/WorldHealthOrganization/ihrbenchmark.git#$(build.SourceVersion)
       - job: Build
         displayName: Build and Push Image
         dependsOn: BuildBase
         condition: ne(variables['Build.Reason'], 'Schedule')
         steps:
-          - task: Docker@2
-            displayName: Login to ACR
+          - script: |
+              if [ -z "$(GITHUB_PAT_EXPIRY)" ]; then
+                echo "GITHUB_PAT_EXPIRY is not set! This is for your own good!"
+                exit 1
+              fi
+
+              echo "GitHub PAT expires on $(GITHUB_PAT_EXPIRY)"
+
+              now=$(date +%s)
+              expiry=$(date -d "$(GITHUB_PAT_EXPIRY)" +%s)
+
+              if [ $expiry -lt $now ]; then
+                echo "GitHub PAT is expired. ACR task will fail to pull from GitHub."
+                echo "Please follow instructions in config/terraform/README.md to update."
+                exit 1
+              fi
+            displayName: Confirm GitHub PAT is not expired
+          - task: AzureCLI@2
+            displayName: Build and push app image to ACR
             inputs:
-              command: login
-              containerRegistry: $(ACR_SERVICE_ENDPOINT_NAME)
-          - task: Docker@2
-            displayName: Docker build image
-            inputs:
-              command: build
-              containerRegistry: $(ACR_SERVICE_ENDPOINT_NAME)
-              repository: $(CONTAINER_REPOSITORY)
-              buildContext: $(Build.Repository.LocalPath)
-              Dockerfile: config/docker/Dockerfile
-              tags: |
-                $(tag)
-                latest
-              arguments: "--no-cache --build-arg COMMIT_SHA=$(Build.SourceVersion) --build-arg DOCKER_IMAGE_TAG=$(tag) --build-arg BUILDER_IMAGE=$(builderImageName)"
-          - task: Docker@2
-            displayName: Docker push image to ACR
-            inputs:
-              command: push
-              containerRegistry: $(ACR_SERVICE_ENDPOINT_NAME)
-              repository: $(CONTAINER_REPOSITORY)
-              tags: |
-                $(tag)
-                latest
-          - task: Docker@2
-            displayName: Logout of ACR
-            inputs:
-              command: logout
-              containerRegistry: $(ACR_SERVICE_ENDPOINT_NAME)
+              azureSubscription: SC-IHRBENCHMARK-P-WEU-RG01
+              scriptType: bash
+              scriptLocation: inlineScript
+              inlineScript: |
+                set -ex
+                az acr task list --registry=$(CONTAINER_REGISTRY_NAME)
+                az acr task run --registry=$(CONTAINER_REGISTRY_NAME) \
+                --name=build-final-image \
+                --context=https://github.com/WorldHealthOrganization/ihrbenchmark.git#$(build.SourceVersion) \
+                --arg COMMIT_SHA=$(Build.SourceVersion) \
+                --arg DOCKER_IMAGE_TAG=$(buildVersionTag) \
+                --arg DOCKER_IMAGE_TAG=$(dockerTag) \
+                --arg BUILDER_IMAGE=$(builderImageName)
   - stage: Staging
-    dependsOn: Build
-    condition: and(succeeded(), ne(variables['Build.Reason'], 'Schedule'))
+    dependsOn:
+      - Test
+      - Build
+    condition: and(eq(variables.isMain, 'true'), and(succeeded(), ne(variables['Build.Reason'], 'Schedule')))
+    pool: uat-agents-no-docker
     jobs:
       - deployment: Stage
         displayName: Deploy to Staging
@@ -207,6 +220,7 @@ stages:
   - stage: Production
     dependsOn: Staging
     condition: and(succeeded(), ne(variables['Build.Reason'], 'Schedule'))
+    pool: prod-agents-no-docker
     jobs:
       - deployment: Promote
         displayName: Promote to production
